#!/bin/bash 

TIME=$(zenity --entry --title="Timer" --text="Enter a duration for the timer.\n\n")
sleep $TIME

zenity --info --title="Timer Complete" --text="Jonas is done fapping.\n\n Jonas wanked for $TIME."
exit 0
