#!/bin/bash 
# Uppgift 1 och 2  i laboration 5
# Av: Oliver Gerling trollface.eu
# Ska mata in en fråga som ber användern om ett tal mellan 10 och 100. med hjälp av en untill loop ska det räknas ner till 1.
# Gör uppgift 1 och 2 samtidigt. 
# ELSE SATS ska göras innan man stänger if satsen. 
clear
echo ""
read -p "Say a number between 10 to 100 please " Number
if [ $Number -gt 100 ];then 
    echo "No time for trolling I'm starving add the correct one ;D"
    exit 1 
elif [ $Number -lt 10 ];then
    echo " You tard :)? "
    exit 1
fi

until [ "$Number" -eq 0 ]; do
    echo "$Number"
    Number=$[ Number -1 ]
done
exit 0
